CREATE TABLE `DBNAME`.`EVENT_LOG` (
  `EVENT_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'generated unique ID',
  `EVENT_TIMESTAMP` DATETIME NULL,
  `EVENT_NICK` VARCHAR(45) NULL,
  `EVENT_MESSAGE` VARCHAR(255) NULL,
  `EVENT_CHANNEL` VARCHAR(45) NULL,
  `EVENT_BOT` VARCHAR(45) NULL,
  `EVENT_TYPE` VARCHAR(45) NULL,
  PRIMARY KEY (`EVENT_ID`),
  UNIQUE INDEX `EVENT_ID_UNIQUE` (`EVENT_ID` ASC))
COMMENT = 'Log of all channel events that logger is running on.';