SELECT * FROM recursi3_rcbot_db.EVENT_LOG WHERE EVENT_TYPE <> 'PING' ORDER BY EVENT_TIMESTAMP DESC;

SELECT * FROM recursi3_rcbot_db.EVENT_LOG WHERE EVENT_CHANNEL = '#StoopTest' ORDER BY EVENT_TIMESTAMP ASC;